"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the map we want to create.
"""

from spg_overlay.entities.normal_wall import SrColorWall, NormalBox


# Dimension of the map : (1000, 700)
# Dimension factor : 1.0
def add_boxes(playground):
    pass


def add_walls(playground):
    # horizontal wall 0
    wall = SrColorWall(pos_start=(-219, 242),
                      pos_end=(-173, 242),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 1
    wall = SrColorWall(pos_start=(-222, 238),
                      pos_end=(-174, 238),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = SrColorWall(pos_start=(-224, 241),
                      pos_end=(-224, 33),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 3
    wall = SrColorWall(pos_start=(-220, 241),
                      pos_end=(-220, 33),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 4
    wall = SrColorWall(pos_start=(-176, 241),
                      pos_end=(-176, 33),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 5
    wall = SrColorWall(pos_start=(-172, 241),
                      pos_end=(-172, 33),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 6
    wall = SrColorWall(pos_start=(103, 215),
                      pos_end=(418, 215),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 7
    wall = SrColorWall(pos_start=(100, 211),
                      pos_end=(417, 211),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 8
    wall = SrColorWall(pos_start=(98, 214),
                      pos_end=(98, 33),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 9
    wall = SrColorWall(pos_start=(102, 214),
                      pos_end=(102, 33),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 10
    wall = SrColorWall(pos_start=(415, 214),
                      pos_end=(415, 164),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 11
    wall = SrColorWall(pos_start=(419, 214),
                      pos_end=(419, 164),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 12
    wall = SrColorWall(pos_start=(151, 167),
                      pos_end=(418, 167),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 13
    wall = SrColorWall(pos_start=(148, 163),
                      pos_end=(417, 163),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 14
    wall = SrColorWall(pos_start=(146, 166),
                      pos_end=(146, 33),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 15
    wall = SrColorWall(pos_start=(150, 166),
                      pos_end=(150, 33),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 16
    wall = SrColorWall(pos_start=(-458, 114),
                      pos_end=(-316, 114),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 17
    wall = SrColorWall(pos_start=(-461, 110),
                      pos_end=(-317, 110),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 18
    wall = SrColorWall(pos_start=(-463, 113),
                      pos_end=(-463, -94),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 19
    wall = SrColorWall(pos_start=(-459, 113),
                      pos_end=(-459, -94),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 20
    wall = SrColorWall(pos_start=(-319, 113),
                      pos_end=(-319, 33),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 21
    wall = SrColorWall(pos_start=(-315, 113),
                      pos_end=(-315, 33),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 22
    wall = SrColorWall(pos_start=(-314, 36),
                      pos_end=(-221, 36),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 23
    wall = SrColorWall(pos_start=(-171, 36),
                      pos_end=(101, 36),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 24
    wall = SrColorWall(pos_start=(151, 36),
                      pos_end=(308, 36),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 25
    wall = SrColorWall(pos_start=(-317, 32),
                      pos_end=(-222, 32),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 26
    wall = SrColorWall(pos_start=(-174, 32),
                      pos_end=(100, 32),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 27
    wall = SrColorWall(pos_start=(148, 32),
                      pos_end=(307, 32),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 28
    wall = SrColorWall(pos_start=(305, 35),
                      pos_end=(305, -126),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 29
    wall = SrColorWall(pos_start=(309, 35),
                      pos_end=(309, -126),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 30
    wall = SrColorWall(pos_start=(-314, -12),
                      pos_end=(-62, -12),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 31
    wall = SrColorWall(pos_start=(-12, -12),
                      pos_end=(260, -12),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 32
    wall = SrColorWall(pos_start=(-317, -16),
                      pos_end=(-63, -16),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 33
    wall = SrColorWall(pos_start=(-15, -16),
                      pos_end=(259, -16),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 34
    wall = SrColorWall(pos_start=(-319, -13),
                      pos_end=(-319, -94),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 35
    wall = SrColorWall(pos_start=(-315, -13),
                      pos_end=(-315, -94),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 36
    wall = SrColorWall(pos_start=(-65, -13),
                      pos_end=(-65, -271),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 37
    wall = SrColorWall(pos_start=(-61, -13),
                      pos_end=(-61, -271),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 38
    wall = SrColorWall(pos_start=(-17, -13),
                      pos_end=(-17, -271),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 39
    wall = SrColorWall(pos_start=(-13, -13),
                      pos_end=(-13, -271),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 40
    wall = SrColorWall(pos_start=(257, -13),
                      pos_end=(257, -174),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 41
    wall = SrColorWall(pos_start=(261, -13),
                      pos_end=(261, -174),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 42
    wall = SrColorWall(pos_start=(-458, -91),
                      pos_end=(-316, -91),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 43
    wall = SrColorWall(pos_start=(-461, -95),
                      pos_end=(-317, -95),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 44
    wall = SrColorWall(pos_start=(310, -123),
                      pos_end=(418, -123),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 45
    wall = SrColorWall(pos_start=(307, -127),
                      pos_end=(417, -127),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 46
    wall = SrColorWall(pos_start=(415, -124),
                      pos_end=(415, -174),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 47
    wall = SrColorWall(pos_start=(419, -124),
                      pos_end=(419, -174),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 48
    wall = SrColorWall(pos_start=(262, -171),
                      pos_end=(418, -171),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 49
    wall = SrColorWall(pos_start=(259, -175),
                      pos_end=(417, -175),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 50
    wall = SrColorWall(pos_start=(-60, -268),
                      pos_end=(-14, -268),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 51
    wall = SrColorWall(pos_start=(-63, -272),
                      pos_end=(-15, -272),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

