"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the map we want to create.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1000, 700)
# Dimension factor : 1.0
def add_boxes(playground):
    pass


def add_walls(playground):
    # horizontal wall 0
    wall = NormalWall(pos_start=(138, 319),
                      pos_end=(440, 319))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 1
    wall = NormalWall(pos_start=(138, 317),
                      pos_end=(439, 317))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(136, 318),
                      pos_end=(136, 250))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 3
    wall = NormalWall(pos_start=(138, 318),
                      pos_end=(138, 250))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 4
    wall = NormalWall(pos_start=(439, 318),
                      pos_end=(439, -74))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 5
    wall = NormalWall(pos_start=(359, -204),
                      pos_end=(441, -67))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 6
    wall = NormalWall(pos_start=(-12, -201),
                      pos_end=(365, -201))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 7
    wall = NormalWall(pos_start=(441, 318),
                      pos_end=(441, -78))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 8
    wall = NormalWall(pos_start=(362, -206),
                      pos_end=(443, -71))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 9
    wall = NormalWall(pos_start=(-464, 300),
                      pos_end=(-293, 300))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 10
    wall = NormalWall(pos_start=(-300, 302),
                      pos_end=(-249, 269))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 11
    wall = NormalWall(pos_start=(-255, 274),
                      pos_end=(75, 274))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 12
    wall = NormalWall(pos_start=(-464, 298),
                      pos_end=(-296, 298))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 13
    wall = NormalWall(pos_start=(-303, 300),
                      pos_end=(-250, 267))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 14
    wall = NormalWall(pos_start=(-256, 272),
                      pos_end=(75, 272))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 15
    wall = NormalWall(pos_start=(-466, 299),
                      pos_end=(-466, 80))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 16
    wall = NormalWall(pos_start=(-464, 299),
                      pos_end=(-464, 80))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 17
    wall = NormalWall(pos_start=(74, 273),
                      pos_end=(74, 205))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 18
    wall = NormalWall(pos_start=(76, 273),
                      pos_end=(76, 205))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 19
    wall = NormalWall(pos_start=(138, 251),
                      pos_end=(372, 251))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 20
    wall = NormalWall(pos_start=(138, 249),
                      pos_end=(371, 249))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 21
    wall = NormalWall(pos_start=(371, 250),
                      pos_end=(371, -59))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 22
    wall = NormalWall(pos_start=(322, -135),
                      pos_end=(373, -52))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 23
    wall = NormalWall(pos_start=(261, -131),
                      pos_end=(328, -131))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 24
    wall = NormalWall(pos_start=(373, 250),
                      pos_end=(373, -61))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 25
    wall = NormalWall(pos_start=(324, -137),
                      pos_end=(375, -54))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 26
    wall = NormalWall(pos_start=(262, -133),
                      pos_end=(330, -133))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 27
    wall = NormalWall(pos_start=(-396, 232),
                      pos_end=(-320, 232))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 28
    wall = NormalWall(pos_start=(-327, 234),
                      pos_end=(-91, 94))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 29
    wall = NormalWall(pos_start=(-396, 230),
                      pos_end=(-323, 230))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 30
    wall = NormalWall(pos_start=(-330, 232),
                      pos_end=(-93, 92))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 31
    wall = NormalWall(pos_start=(-398, 231),
                      pos_end=(-398, 148))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 32
    wall = NormalWall(pos_start=(-396, 231),
                      pos_end=(-396, 148))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 33
    wall = NormalWall(pos_start=(143, 221),
                      pos_end=(307, 221))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 34
    wall = NormalWall(pos_start=(143, 219),
                      pos_end=(306, 219))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 35
    wall = NormalWall(pos_start=(141, 220),
                      pos_end=(141, 4))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 36
    wall = NormalWall(pos_start=(143, 220),
                      pos_end=(143, 4))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 37
    wall = NormalWall(pos_start=(306, 220),
                      pos_end=(306, 4))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 38
    wall = NormalWall(pos_start=(308, 220),
                      pos_end=(308, 4))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 39
    wall = NormalWall(pos_start=(-164, 206),
                      pos_end=(75, 206))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 40
    wall = NormalWall(pos_start=(-135, 208),
                      pos_end=(-135, 187))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 41
    wall = NormalWall(pos_start=(-137, 194),
                      pos_end=(7, 107))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 42
    wall = NormalWall(pos_start=(2, 113),
                      pos_end=(2, 89))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 43
    wall = NormalWall(pos_start=(-138, 204),
                      pos_end=(74, 204))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 44
    wall = NormalWall(pos_start=(-164, 207),
                      pos_end=(3, 106))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 45
    wall = NormalWall(pos_start=(-2, 112),
                      pos_end=(-2, 89))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 46
    wall = NormalWall(pos_start=(-396, 149),
                      pos_end=(-269, 149))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 47
    wall = NormalWall(pos_start=(-396, 147),
                      pos_end=(-270, 147))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 48
    wall = NormalWall(pos_start=(-270, 148),
                      pos_end=(-270, 80))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 49
    wall = NormalWall(pos_start=(-268, 148),
                      pos_end=(-268, 80))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 50
    wall = NormalWall(pos_start=(-101, 80),
                      pos_end=(-91, 100))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 51
    wall = NormalWall(pos_start=(-205, -22),
                      pos_end=(-95, 88))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 52
    wall = NormalWall(pos_start=(-140, -46),
                      pos_end=(1, 96))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 53
    wall = NormalWall(pos_start=(-202, -24),
                      pos_end=(-84, 94))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 54
    wall = NormalWall(pos_start=(-135, -45),
                      pos_end=(6, 96))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 55
    wall = NormalWall(pos_start=(-464, 81),
                      pos_end=(-269, 81))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 56
    wall = NormalWall(pos_start=(-464, 79),
                      pos_end=(-270, 79))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 57
    wall = NormalWall(pos_start=(-454, 37),
                      pos_end=(-318, 37))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 58
    wall = NormalWall(pos_start=(-454, 35),
                      pos_end=(-319, 35))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 59
    wall = NormalWall(pos_start=(-456, 36),
                      pos_end=(-456, -152))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 60
    wall = NormalWall(pos_start=(-454, 36),
                      pos_end=(-454, -152))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 61
    wall = NormalWall(pos_start=(-319, 36),
                      pos_end=(-319, -22))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 62
    wall = NormalWall(pos_start=(-317, 36),
                      pos_end=(-317, -22))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 63
    wall = NormalWall(pos_start=(143, 5),
                      pos_end=(193, 5))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 64
    wall = NormalWall(pos_start=(262, 5),
                      pos_end=(307, 5))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 65
    wall = NormalWall(pos_start=(143, 3),
                      pos_end=(192, 3))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 66
    wall = NormalWall(pos_start=(262, 3),
                      pos_end=(306, 3))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 67
    wall = NormalWall(pos_start=(192, 4),
                      pos_end=(192, -134))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 68
    wall = NormalWall(pos_start=(194, 4),
                      pos_end=(194, -134))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 69
    wall = NormalWall(pos_start=(260, 4),
                      pos_end=(260, -132))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 70
    wall = NormalWall(pos_start=(262, 4),
                      pos_end=(262, -132))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 71
    wall = NormalWall(pos_start=(-317, -21),
                      pos_end=(-200, -21))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 72
    wall = NormalWall(pos_start=(-317, -23),
                      pos_end=(-201, -23))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 73
    wall = NormalWall(pos_start=(-138, -47),
                      pos_end=(14, -138))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 74
    wall = NormalWall(pos_start=(8, -135),
                      pos_end=(193, -135))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 75
    wall = NormalWall(pos_start=(-132, -47),
                      pos_end=(15, -135))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 76
    wall = NormalWall(pos_start=(10, -133),
                      pos_end=(193, -133))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 77
    wall = NormalWall(pos_start=(-317, -89),
                      pos_end=(-199, -89))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 78
    wall = NormalWall(pos_start=(-317, -91),
                      pos_end=(-200, -91))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 79
    wall = NormalWall(pos_start=(-202, -88),
                      pos_end=(-6, -205))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 80
    wall = NormalWall(pos_start=(-319, -90),
                      pos_end=(-319, -152))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 81
    wall = NormalWall(pos_start=(-317, -90),
                      pos_end=(-317, -152))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 82
    wall = NormalWall(pos_start=(-203, -90),
                      pos_end=(-6, -208))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 83
    wall = NormalWall(pos_start=(-12, -203),
                      pos_end=(366, -203))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 84
    wall = NormalWall(pos_start=(-454, -151),
                      pos_end=(-318, -151))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 85
    wall = NormalWall(pos_start=(-454, -153),
                      pos_end=(-319, -153))
    playground.add(wall, wall.wall_coordinates)

