"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the map we want to create.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1000, 700)
# Dimension factor : 1.0
def add_boxes(playground):
    pass


def add_walls(playground):
    # vertical wall 0
    wall = NormalWall(pos_start=(-485, 336),
                      pos_end=(-485, -336))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 1
    wall = NormalWall(pos_start=(-484, 333),
                      pos_end=(489, 333))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(485, 335),
                      pos_end=(485, -336))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 3
    wall = NormalWall(pos_start=(18, 222),
                      pos_end=(18, 178))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 4
    wall = NormalWall(pos_start=(21, 220),
                      pos_end=(112, 220))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 5
    wall = NormalWall(pos_start=(111, 222),
                      pos_end=(111, 52))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 6
    wall = NormalWall(pos_start=(110, 56),
                      pos_end=(331, 56))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 7
    wall = NormalWall(pos_start=(331, 57),
                      pos_end=(331, -135))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 8
    wall = NormalWall(pos_start=(22, 220),
                      pos_end=(22, 179))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 9
    wall = NormalWall(pos_start=(19, 216),
                      pos_end=(111, 216))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 10
    wall = NormalWall(pos_start=(107, 219),
                      pos_end=(107, 51))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 11
    wall = NormalWall(pos_start=(105, 52),
                      pos_end=(331, 52))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 12
    wall = NormalWall(pos_start=(327, 54),
                      pos_end=(327, -134))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 13
    wall = NormalWall(pos_start=(19, 183),
                      pos_end=(68, 183))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 14
    wall = NormalWall(pos_start=(67, 185),
                      pos_end=(67, 49))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 15
    wall = NormalWall(pos_start=(17, 179),
                      pos_end=(67, 179))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 16
    wall = NormalWall(pos_start=(63, 181),
                      pos_end=(63, 50))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 17
    wall = NormalWall(pos_start=(-120, 161),
                      pos_end=(-120, 48))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 18
    wall = NormalWall(pos_start=(-117, 159),
                      pos_end=(-63, 159))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 19
    wall = NormalWall(pos_start=(-64, 161),
                      pos_end=(-64, 50))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 20
    wall = NormalWall(pos_start=(-66, 54),
                      pos_end=(66, 54))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 21
    wall = NormalWall(pos_start=(-116, 159),
                      pos_end=(-116, 47))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 22
    wall = NormalWall(pos_start=(-189, 48),
                      pos_end=(-114, 48))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 23
    wall = NormalWall(pos_start=(-119, 155),
                      pos_end=(-64, 155))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 24
    wall = NormalWall(pos_start=(-68, 158),
                      pos_end=(-68, 49))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 25
    wall = NormalWall(pos_start=(-70, 50),
                      pos_end=(67, 50))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 26
    wall = NormalWall(pos_start=(-370, 113),
                      pos_end=(-370, -53))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 27
    wall = NormalWall(pos_start=(-368, 110),
                      pos_end=(-257, 110))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 28
    wall = NormalWall(pos_start=(-258, 112),
                      pos_end=(-258, 48))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 29
    wall = NormalWall(pos_start=(-259, 52),
                      pos_end=(-118, 52))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 30
    wall = NormalWall(pos_start=(-366, 110),
                      pos_end=(-366, -52))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 31
    wall = NormalWall(pos_start=(-369, 106),
                      pos_end=(-258, 106))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 32
    wall = NormalWall(pos_start=(-262, 109),
                      pos_end=(-262, 46))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 33
    wall = NormalWall(pos_start=(-262, 50),
                      pos_end=(-182, 50))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 34
    wall = NormalWall(pos_start=(-262, 13),
                      pos_end=(-262, -52))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 35
    wall = NormalWall(pos_start=(-369, -48),
                      pos_end=(-260, -48))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 36
    wall = NormalWall(pos_start=(-262, 11),
                      pos_end=(-32, 11))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 37
    wall = NormalWall(pos_start=(-33, 13),
                      pos_end=(-33, -77))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 38
    wall = NormalWall(pos_start=(-35, -73),
                      pos_end=(6, -73))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 39
    wall = NormalWall(pos_start=(2, 12),
                      pos_end=(2, -76))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 40
    wall = NormalWall(pos_start=(5, 10),
                      pos_end=(280, 10))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 41
    wall = NormalWall(pos_start=(279, 12),
                      pos_end=(279, -90))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 42
    wall = NormalWall(pos_start=(-258, 11),
                      pos_end=(-258, -53))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 43
    wall = NormalWall(pos_start=(-370, -52),
                      pos_end=(-256, -52))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 44
    wall = NormalWall(pos_start=(-261, 7),
                      pos_end=(-33, 7))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 45
    wall = NormalWall(pos_start=(-37, 10),
                      pos_end=(-37, -78))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 46
    wall = NormalWall(pos_start=(-39, -77),
                      pos_end=(4, -77))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 47
    wall = NormalWall(pos_start=(6, 10),
                      pos_end=(6, -78))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 48
    wall = NormalWall(pos_start=(3, 6),
                      pos_end=(279, 6))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 49
    wall = NormalWall(pos_start=(275, 9),
                      pos_end=(275, -92))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 50
    wall = NormalWall(pos_start=(233, -92),
                      pos_end=(281, -92))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 51
    wall = NormalWall(pos_start=(237, -91),
                      pos_end=(237, -132))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 52
    wall = NormalWall(pos_start=(233, -86),
                      pos_end=(233, -133))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 53
    wall = NormalWall(pos_start=(236, -88),
                      pos_end=(278, -88))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 54
    wall = NormalWall(pos_start=(234, -129),
                      pos_end=(330, -129))
    playground.add(wall, wall.wall_coordinates)

    # oblique wall 55
    wall = NormalWall(pos_start=(232, -127),
                      pos_end=(331, -138))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 56
    wall = NormalWall(pos_start=(-487, -332),
                      pos_end=(488, -332))
    playground.add(wall, wall.wall_coordinates)

