"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the map we want to create.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1000, 700)
# Dimension factor : 1.0
def add_boxes(playground):
    pass


def add_walls(playground):
    # horizontal wall 0
    wall = NormalWall(pos_start=(-178, 328),
                      pos_end=(-109, 328))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 1
    wall = NormalWall(pos_start=(-178, 326),
                      pos_end=(-110, 326))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = NormalWall(pos_start=(-180, 327),
                      pos_end=(-180, 49))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 3
    wall = NormalWall(pos_start=(-178, 327),
                      pos_end=(-178, 49))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 4
    wall = NormalWall(pos_start=(-110, 327),
                      pos_end=(-110, 49))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 5
    wall = NormalWall(pos_start=(-108, 327),
                      pos_end=(-108, 49))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 6
    wall = NormalWall(pos_start=(141, 309),
                      pos_end=(409, 309))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 7
    wall = NormalWall(pos_start=(141, 307),
                      pos_end=(408, 307))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 8
    wall = NormalWall(pos_start=(139, 308),
                      pos_end=(139, 49))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 9
    wall = NormalWall(pos_start=(141, 308),
                      pos_end=(141, 49))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 10
    wall = NormalWall(pos_start=(408, 308),
                      pos_end=(408, 238))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 11
    wall = NormalWall(pos_start=(410, 308),
                      pos_end=(410, 238))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 12
    wall = NormalWall(pos_start=(211, 239),
                      pos_end=(409, 239))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 13
    wall = NormalWall(pos_start=(211, 237),
                      pos_end=(408, 237))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 14
    wall = NormalWall(pos_start=(209, 238),
                      pos_end=(209, 49))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 15
    wall = NormalWall(pos_start=(211, 238),
                      pos_end=(211, 49))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 16
    wall = NormalWall(pos_start=(-448, 173),
                      pos_end=(-251, 173))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 17
    wall = NormalWall(pos_start=(-448, 171),
                      pos_end=(-252, 171))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 18
    wall = NormalWall(pos_start=(-450, 172),
                      pos_end=(-450, -144))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 19
    wall = NormalWall(pos_start=(-448, 172),
                      pos_end=(-448, -144))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 20
    wall = NormalWall(pos_start=(-252, 172),
                      pos_end=(-252, 49))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 21
    wall = NormalWall(pos_start=(-250, 172),
                      pos_end=(-250, 49))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 22
    wall = NormalWall(pos_start=(-250, 50),
                      pos_end=(-179, 50))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 23
    wall = NormalWall(pos_start=(-108, 50),
                      pos_end=(140, 50))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 24
    wall = NormalWall(pos_start=(211, 50),
                      pos_end=(346, 50))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 25
    wall = NormalWall(pos_start=(-250, 48),
                      pos_end=(-180, 48))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 26
    wall = NormalWall(pos_start=(-108, 48),
                      pos_end=(139, 48))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 27
    wall = NormalWall(pos_start=(211, 48),
                      pos_end=(345, 48))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 28
    wall = NormalWall(pos_start=(345, 49),
                      pos_end=(345, -153))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 29
    wall = NormalWall(pos_start=(347, 49),
                      pos_end=(347, -153))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 30
    wall = NormalWall(pos_start=(-250, -20),
                      pos_end=(-13, -20))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 31
    wall = NormalWall(pos_start=(58, -20),
                      pos_end=(276, -20))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 32
    wall = NormalWall(pos_start=(-250, -22),
                      pos_end=(-14, -22))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 33
    wall = NormalWall(pos_start=(58, -22),
                      pos_end=(275, -22))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 34
    wall = NormalWall(pos_start=(-252, -21),
                      pos_end=(-252, -144))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 35
    wall = NormalWall(pos_start=(-250, -21),
                      pos_end=(-250, -144))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 36
    wall = NormalWall(pos_start=(-14, -21),
                      pos_end=(-14, -329))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 37
    wall = NormalWall(pos_start=(-12, -21),
                      pos_end=(-12, -329))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 38
    wall = NormalWall(pos_start=(56, -21),
                      pos_end=(56, -329))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 39
    wall = NormalWall(pos_start=(58, -21),
                      pos_end=(58, -329))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 40
    wall = NormalWall(pos_start=(275, -21),
                      pos_end=(275, -223))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 41
    wall = NormalWall(pos_start=(277, -21),
                      pos_end=(277, -223))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 42
    wall = NormalWall(pos_start=(-448, -143),
                      pos_end=(-251, -143))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 43
    wall = NormalWall(pos_start=(-448, -145),
                      pos_end=(-252, -145))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 44
    wall = NormalWall(pos_start=(347, -152),
                      pos_end=(464, -152))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 45
    wall = NormalWall(pos_start=(347, -154),
                      pos_end=(463, -154))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 46
    wall = NormalWall(pos_start=(463, -153),
                      pos_end=(463, -223))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 47
    wall = NormalWall(pos_start=(465, -153),
                      pos_end=(465, -223))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 48
    wall = NormalWall(pos_start=(277, -222),
                      pos_end=(464, -222))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 49
    wall = NormalWall(pos_start=(277, -224),
                      pos_end=(463, -224))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 50
    wall = NormalWall(pos_start=(-12, -328),
                      pos_end=(57, -328))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 51
    wall = NormalWall(pos_start=(-12, -330),
                      pos_end=(56, -330))
    playground.add(wall, wall.wall_coordinates)

