"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the map we want to create.
"""

from spg_overlay.entities.normal_wall import NormalWall, NormalBox


# Dimension of the map : (1000, 700)
# Dimension factor : 1.0
def add_boxes(playground):
    pass


def add_walls(playground):
    # horizontal wall 0
    wall = NormalWall(pos_start=(-149, 336),
                      pos_end=(-82, 336))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 1
    wall = NormalWall(pos_start=(-149, 334),
                      pos_end=(-83, 334))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 2
    wall = NormalWall(pos_start=(-448, 331),
                      pos_end=(-188, 331))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 3
    wall = NormalWall(pos_start=(-151, 335),
                      pos_end=(-151, 182))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 4
    wall = NormalWall(pos_start=(-149, 335),
                      pos_end=(-149, 182))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 5
    wall = NormalWall(pos_start=(-83, 335),
                      pos_end=(-83, 12))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 6
    wall = NormalWall(pos_start=(-81, 335),
                      pos_end=(-81, 12))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 7
    wall = NormalWall(pos_start=(-448, 329),
                      pos_end=(-189, 329))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 8
    wall = NormalWall(pos_start=(-450, 330),
                      pos_end=(-450, 114))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 9
    wall = NormalWall(pos_start=(-448, 330),
                      pos_end=(-448, 114))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 10
    wall = NormalWall(pos_start=(-189, 330),
                      pos_end=(-189, 262))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 11
    wall = NormalWall(pos_start=(-187, 330),
                      pos_end=(-187, 262))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 12
    wall = NormalWall(pos_start=(-50, 309),
                      pos_end=(171, 309))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 13
    wall = NormalWall(pos_start=(-50, 307),
                      pos_end=(170, 307))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 14
    wall = NormalWall(pos_start=(-52, 308),
                      pos_end=(-52, 240))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 15
    wall = NormalWall(pos_start=(-50, 308),
                      pos_end=(-50, 240))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 16
    wall = NormalWall(pos_start=(170, 308),
                      pos_end=(170, 119))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 17
    wall = NormalWall(pos_start=(172, 308),
                      pos_end=(172, 119))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 18
    wall = NormalWall(pos_start=(314, 273),
                      pos_end=(483, 273))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 19
    wall = NormalWall(pos_start=(314, 271),
                      pos_end=(482, 271))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 20
    wall = NormalWall(pos_start=(312, 272),
                      pos_end=(312, 119))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 21
    wall = NormalWall(pos_start=(314, 272),
                      pos_end=(314, 119))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 22
    wall = NormalWall(pos_start=(482, 272),
                      pos_end=(482, 204))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 23
    wall = NormalWall(pos_start=(484, 272),
                      pos_end=(484, 204))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 24
    wall = NormalWall(pos_start=(-380, 263),
                      pos_end=(-188, 263))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 25
    wall = NormalWall(pos_start=(-380, 261),
                      pos_end=(-189, 261))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 26
    wall = NormalWall(pos_start=(-382, 262),
                      pos_end=(-382, 182))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 27
    wall = NormalWall(pos_start=(-380, 262),
                      pos_end=(-380, 182))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 28
    wall = NormalWall(pos_start=(-50, 241),
                      pos_end=(103, 241))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 29
    wall = NormalWall(pos_start=(-50, 239),
                      pos_end=(102, 239))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 30
    wall = NormalWall(pos_start=(102, 240),
                      pos_end=(102, 51))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 31
    wall = NormalWall(pos_start=(104, 240),
                      pos_end=(104, 51))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 32
    wall = NormalWall(pos_start=(382, 205),
                      pos_end=(483, 205))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 33
    wall = NormalWall(pos_start=(382, 203),
                      pos_end=(482, 203))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 34
    wall = NormalWall(pos_start=(380, 204),
                      pos_end=(380, -301))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 35
    wall = NormalWall(pos_start=(382, 204),
                      pos_end=(382, -301))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 36
    wall = NormalWall(pos_start=(-380, 183),
                      pos_end=(-150, 183))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 37
    wall = NormalWall(pos_start=(-380, 181),
                      pos_end=(-151, 181))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 38
    wall = NormalWall(pos_start=(172, 120),
                      pos_end=(313, 120))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 39
    wall = NormalWall(pos_start=(172, 118),
                      pos_end=(312, 118))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 40
    wall = NormalWall(pos_start=(-448, 115),
                      pos_end=(-150, 115))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 41
    wall = NormalWall(pos_start=(-448, 113),
                      pos_end=(-151, 113))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 42
    wall = NormalWall(pos_start=(-151, 114),
                      pos_end=(-151, 12))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 43
    wall = NormalWall(pos_start=(-149, 114),
                      pos_end=(-149, 12))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 44
    wall = NormalWall(pos_start=(-451, 71),
                      pos_end=(-288, 71))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 45
    wall = NormalWall(pos_start=(-451, 69),
                      pos_end=(-289, 69))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 46
    wall = NormalWall(pos_start=(-453, 70),
                      pos_end=(-453, -113))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 47
    wall = NormalWall(pos_start=(-451, 70),
                      pos_end=(-451, -113))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 48
    wall = NormalWall(pos_start=(-289, 70),
                      pos_end=(-289, 12))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 49
    wall = NormalWall(pos_start=(-287, 70),
                      pos_end=(-287, 12))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 50
    wall = NormalWall(pos_start=(104, 52),
                      pos_end=(313, 52))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 51
    wall = NormalWall(pos_start=(104, 50),
                      pos_end=(312, 50))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 52
    wall = NormalWall(pos_start=(312, 51),
                      pos_end=(312, 12))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 53
    wall = NormalWall(pos_start=(314, 51),
                      pos_end=(314, 12))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 54
    wall = NormalWall(pos_start=(-287, 13),
                      pos_end=(-150, 13))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 55
    wall = NormalWall(pos_start=(-81, 13),
                      pos_end=(313, 13))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 56
    wall = NormalWall(pos_start=(-287, 11),
                      pos_end=(-151, 11))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 57
    wall = NormalWall(pos_start=(-81, 11),
                      pos_end=(312, 11))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 58
    wall = NormalWall(pos_start=(-287, -55),
                      pos_end=(-150, -55))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 59
    wall = NormalWall(pos_start=(-81, -55),
                      pos_end=(313, -55))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 60
    wall = NormalWall(pos_start=(-287, -57),
                      pos_end=(-151, -57))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 61
    wall = NormalWall(pos_start=(-81, -57),
                      pos_end=(312, -57))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 62
    wall = NormalWall(pos_start=(-289, -56),
                      pos_end=(-289, -113))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 63
    wall = NormalWall(pos_start=(-287, -56),
                      pos_end=(-287, -113))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 64
    wall = NormalWall(pos_start=(-151, -56),
                      pos_end=(-151, -134))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 65
    wall = NormalWall(pos_start=(-149, -56),
                      pos_end=(-149, -134))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 66
    wall = NormalWall(pos_start=(-83, -56),
                      pos_end=(-83, -134))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 67
    wall = NormalWall(pos_start=(-81, -56),
                      pos_end=(-81, -134))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 68
    wall = NormalWall(pos_start=(312, -56),
                      pos_end=(312, -233))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 69
    wall = NormalWall(pos_start=(314, -56),
                      pos_end=(314, -233))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 70
    wall = NormalWall(pos_start=(-451, -112),
                      pos_end=(-288, -112))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 71
    wall = NormalWall(pos_start=(-451, -114),
                      pos_end=(-289, -114))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 72
    wall = NormalWall(pos_start=(-452, -133),
                      pos_end=(-150, -133))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 73
    wall = NormalWall(pos_start=(-81, -133),
                      pos_end=(290, -133))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 74
    wall = NormalWall(pos_start=(-452, -135),
                      pos_end=(-151, -135))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 75
    wall = NormalWall(pos_start=(-81, -135),
                      pos_end=(289, -135))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 76
    wall = NormalWall(pos_start=(-454, -134),
                      pos_end=(-454, -202))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 77
    wall = NormalWall(pos_start=(-452, -134),
                      pos_end=(-452, -202))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 78
    wall = NormalWall(pos_start=(289, -134),
                      pos_end=(289, -202))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 79
    wall = NormalWall(pos_start=(291, -134),
                      pos_end=(291, -202))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 80
    wall = NormalWall(pos_start=(-452, -201),
                      pos_end=(-150, -201))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 81
    wall = NormalWall(pos_start=(-81, -201),
                      pos_end=(63, -201))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 82
    wall = NormalWall(pos_start=(132, -201),
                      pos_end=(290, -201))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 83
    wall = NormalWall(pos_start=(-452, -203),
                      pos_end=(-151, -203))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 84
    wall = NormalWall(pos_start=(-81, -203),
                      pos_end=(62, -203))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 85
    wall = NormalWall(pos_start=(132, -203),
                      pos_end=(289, -203))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 86
    wall = NormalWall(pos_start=(-151, -202),
                      pos_end=(-151, -289))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 87
    wall = NormalWall(pos_start=(-149, -202),
                      pos_end=(-149, -289))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 88
    wall = NormalWall(pos_start=(-83, -202),
                      pos_end=(-83, -289))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 89
    wall = NormalWall(pos_start=(-81, -202),
                      pos_end=(-81, -289))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 90
    wall = NormalWall(pos_start=(62, -202),
                      pos_end=(62, -332))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 91
    wall = NormalWall(pos_start=(64, -202),
                      pos_end=(64, -332))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 92
    wall = NormalWall(pos_start=(130, -202),
                      pos_end=(130, -332))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 93
    wall = NormalWall(pos_start=(132, -202),
                      pos_end=(132, -332))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 94
    wall = NormalWall(pos_start=(173, -232),
                      pos_end=(313, -232))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 95
    wall = NormalWall(pos_start=(173, -234),
                      pos_end=(312, -234))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 96
    wall = NormalWall(pos_start=(171, -233),
                      pos_end=(171, -301))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 97
    wall = NormalWall(pos_start=(173, -233),
                      pos_end=(173, -301))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 98
    wall = NormalWall(pos_start=(-149, -288),
                      pos_end=(-82, -288))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 99
    wall = NormalWall(pos_start=(-149, -290),
                      pos_end=(-83, -290))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 100
    wall = NormalWall(pos_start=(173, -300),
                      pos_end=(381, -300))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 101
    wall = NormalWall(pos_start=(173, -302),
                      pos_end=(380, -302))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 102
    wall = NormalWall(pos_start=(64, -331),
                      pos_end=(131, -331))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 103
    wall = NormalWall(pos_start=(64, -333),
                      pos_end=(130, -333))
    playground.add(wall, wall.wall_coordinates)

