"""
This file was generated by the tool 'image_to_map.py' in the directory tools.
This tool permits to create this kind of file by providing it an image of the map we want to create.
"""

from spg_overlay.entities.normal_wall import SrColorWall, NormalBox


# Dimension of the map : (1000, 700)
# Dimension factor : 1.0
def add_boxes(playground):
    pass


def add_walls(playground):
    # vertical wall 0
    wall = SrColorWall(pos_start=(-157, 176),
                      pos_end=(-157, 33),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 1
    wall = SrColorWall(pos_start=(-153, 176),
                      pos_end=(-153, 33),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 2
    wall = SrColorWall(pos_start=(33, 172),
                      pos_end=(33, 32),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 3
    wall = SrColorWall(pos_start=(-70, 36),
                      pos_end=(35, 36),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 4
    wall = SrColorWall(pos_start=(37, 172),
                      pos_end=(37, 29),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 5
    wall = SrColorWall(pos_start=(295, 165),
                      pos_end=(295, 35),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 6
    wall = SrColorWall(pos_start=(299, 165),
                      pos_end=(299, 35),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 7
    wall = SrColorWall(pos_start=(124, 38),
                      pos_end=(298, 38),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 8
    wall = SrColorWall(pos_start=(-309, 36),
                      pos_end=(-154, 36),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 9
    wall = SrColorWall(pos_start=(121, 34),
                      pos_end=(297, 34),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 10
    wall = SrColorWall(pos_start=(-312, 32),
                      pos_end=(-155, 32),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 11
    wall = SrColorWall(pos_start=(-70, 32),
                      pos_end=(39, 32),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 12
    wall = SrColorWall(pos_start=(-202, 10),
                      pos_end=(-202, -101),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 13
    wall = SrColorWall(pos_start=(-198, 10),
                      pos_end=(-198, -101),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 14
    wall = SrColorWall(pos_start=(29, 4),
                      pos_end=(29, -105),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 15
    wall = SrColorWall(pos_start=(33, 4),
                      pos_end=(33, -105),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 16
    wall = SrColorWall(pos_start=(-302, -98),
                      pos_end=(-199, -98),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 17
    wall = SrColorWall(pos_start=(-305, -102),
                      pos_end=(-200, -102),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 18
    wall = SrColorWall(pos_start=(-81, -102),
                      pos_end=(32, -102),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 19
    wall = SrColorWall(pos_start=(-84, -106),
                      pos_end=(31, -106),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 20
    wall = SrColorWall(pos_start=(28, -127),
                      pos_end=(28, -218),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 21
    wall = SrColorWall(pos_start=(32, -127),
                      pos_end=(32, -218),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 22
    wall = SrColorWall(pos_start=(-209, -131),
                      pos_end=(-209, -221),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # vertical wall 23
    wall = SrColorWall(pos_start=(-205, -131),
                      pos_end=(-205, -221),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 24
    wall = SrColorWall(pos_start=(-78, -215),
                      pos_end=(31, -215),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 25
    wall = SrColorWall(pos_start=(-306, -218),
                      pos_end=(-206, -218),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 26
    wall = SrColorWall(pos_start=(-81, -219),
                      pos_end=(30, -219),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

    # horizontal wall 27
    wall = SrColorWall(pos_start=(-309, -222),
                      pos_end=(-207, -222),
                      width = 6, color = (0,0,0))
    playground.add(wall, wall.wall_coordinates)

